// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PentestHub.API.Data;

#nullable disable

namespace PentestHub.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251207184725_AddToolPackageData")]
    partial class AddToolPackageData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("PentestHub.API.Data.Models.AIConversation", b =>
                {
                    b.Property<int>("MsgId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MsgId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponseText")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("MsgId");

                    b.HasIndex("UserId");

                    b.ToTable("AIConversations");
                });

            modelBuilder.Entity("PentestHub.API.Data.Models.KnowledgeBase", b =>
                {
                    b.Property<int>("KnowledgeBaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("KnowledgeBaseId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("KnowledgeBaseId");

                    b.ToTable("KnowledgeBases");
                });

            modelBuilder.Entity("PentestHub.API.Data.Models.Lab", b =>
                {
                    b.Property<int>("LabId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("LabId"));

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("Difficulty")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("LabType")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("LabId");

                    b.ToTable("Labs");

                    b.HasData(
                        new
                        {
                            LabId = 1,
                            Category = "Web Security",
                            Description = "Practice identifying and exploiting SQL injection vulnerabilities in a vulnerable web application. Learn to use tools like SQLMap and manual techniques.",
                            Difficulty = "Beginner",
                            LabType = "Web Application",
                            Title = "SQL Injection Challenge"
                        },
                        new
                        {
                            LabId = 2,
                            Category = "Network Security",
                            Description = "Perform a complete network penetration test on a simulated corporate network. Practice reconnaissance, scanning, exploitation, and post-exploitation.",
                            Difficulty = "Intermediate",
                            LabType = "Network",
                            Title = "Network Penetration Testing"
                        },
                        new
                        {
                            LabId = 3,
                            Category = "Web Security",
                            Description = "Learn to identify and exploit various types of XSS vulnerabilities including reflected, stored, and DOM-based XSS attacks.",
                            Difficulty = "Beginner",
                            LabType = "Web Application",
                            Title = "XSS (Cross-Site Scripting) Exploitation"
                        },
                        new
                        {
                            LabId = 4,
                            Category = "Reconnaissance",
                            Description = "Conduct an open-source intelligence gathering exercise. Practice using tools like theHarvester, Shodan, and social media reconnaissance.",
                            Difficulty = "Beginner",
                            LabType = "OSINT",
                            Title = "OSINT Investigation"
                        },
                        new
                        {
                            LabId = 5,
                            Category = "Post-Exploitation",
                            Description = "Practice advanced Active Directory attack techniques including Kerberoasting, AS-REP Roasting, and lateral movement strategies.",
                            Difficulty = "Advanced",
                            LabType = "Windows",
                            Title = "Active Directory Exploitation"
                        },
                        new
                        {
                            LabId = 6,
                            Category = "Exploitation",
                            Description = "Learn buffer overflow exploitation techniques on Linux systems. Practice stack-based overflows, ROP chains, and shellcode development.",
                            Difficulty = "Advanced",
                            LabType = "Binary Exploitation",
                            Title = "Buffer Overflow Exploitation"
                        },
                        new
                        {
                            LabId = 7,
                            Category = "Wireless",
                            Description = "Practice WiFi security assessment including WPA2/WPA3 cracking, rogue access point detection, and wireless protocol analysis.",
                            Difficulty = "Intermediate",
                            LabType = "Wireless",
                            Title = "Wireless Network Security"
                        },
                        new
                        {
                            LabId = 8,
                            Category = "Web Security",
                            Description = "Learn to test REST and GraphQL APIs for common vulnerabilities including authentication bypass, authorization flaws, and injection attacks.",
                            Difficulty = "Intermediate",
                            LabType = "API",
                            Title = "API Security Testing"
                        },
                        new
                        {
                            LabId = 9,
                            Category = "Cryptography",
                            Description = "Solve cryptographic challenges including cipher decryption, hash analysis, RSA key recovery, and digital signature verification.",
                            Difficulty = "Intermediate",
                            LabType = "Cryptography",
                            Title = "Cryptography Challenge"
                        },
                        new
                        {
                            LabId = 10,
                            Category = "Reverse Engineering",
                            Description = "Practice reverse engineering techniques on malware samples and crackmes. Learn to use tools like Ghidra, IDA Pro, and x64dbg.",
                            Difficulty = "Advanced",
                            LabType = "Reverse Engineering",
                            Title = "Reverse Engineering"
                        });
                });

            modelBuilder.Entity("PentestHub.API.Data.Models.LabResult", b =>
                {
                    b.Property<int>("ResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ResultId"));

                    b.Property<string>("AIFeedback")
                        .HasColumnType("LONGTEXT");

                    b.Property<DateTime?>("CompletionTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Details")
                        .HasColumnType("LONGTEXT");

                    b.Property<int>("LabId")
                        .HasColumnType("int");

                    b.Property<int?>("Score")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ResultId");

                    b.HasIndex("LabId");

                    b.HasIndex("UserId");

                    b.ToTable("LabResults");
                });

            modelBuilder.Entity("PentestHub.API.Data.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Message")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("NotificationId");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("PentestHub.API.Data.Models.Report", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ReportId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PdfPath")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("ScanId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ReportId");

                    b.HasIndex("ScanId");

                    b.HasIndex("UserId");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("PentestHub.API.Data.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("RoleId");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            RoleName = "Admin"
                        },
                        new
                        {
                            RoleId = 2,
                            RoleName = "Learner"
                        },
                        new
                        {
                            RoleId = 3,
                            RoleName = "Professional"
                        });
                });

            modelBuilder.Entity("PentestHub.API.Data.Models.ScanHistory", b =>
                {
                    b.Property<int>("ScanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ScanId"));

                    b.Property<string>("AINextSteps")
                        .HasColumnType("longtext");

                    b.Property<string>("AISummary")
                        .HasColumnType("longtext");

                    b.Property<string>("Arguments")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RawOutput")
                        .HasColumnType("LONGTEXT");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("ToolId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ScanId");

                    b.HasIndex("ToolId");

                    b.HasIndex("UserId");

                    b.ToTable("ScanHistory");
                });

            modelBuilder.Entity("PentestHub.API.Data.Models.Tool", b =>
                {
                    b.Property<int>("ToolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ToolId"));

                    b.Property<string>("BinaryName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("DownloadUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<byte[]>("PackageData")
                        .HasColumnType("LONGBLOB");

                    b.Property<string>("RequiredExtensions")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ToolName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("ToolId");

                    b.ToTable("Tools");

                    b.HasData(
                        new
                        {
                            ToolId = 1,
                            Category = "Network",
                            Description = "Network mapper and port scanner",
                            ToolName = "Nmap"
                        },
                        new
                        {
                            ToolId = 2,
                            Category = "Exploitation",
                            Description = "Penetration testing framework",
                            ToolName = "Metasploit"
                        },
                        new
                        {
                            ToolId = 3,
                            Category = "Web",
                            Description = "Web application security testing",
                            ToolName = "Burp Suite"
                        },
                        new
                        {
                            ToolId = 4,
                            Category = "Network",
                            Description = "Network protocol analyzer",
                            ToolName = "Wireshark"
                        },
                        new
                        {
                            ToolId = 5,
                            Category = "Wireless",
                            Description = "WiFi security auditing",
                            ToolName = "Aircrack-ng"
                        },
                        new
                        {
                            ToolId = 6,
                            Category = "Password",
                            Description = "Password cracking",
                            ToolName = "John the Ripper"
                        },
                        new
                        {
                            ToolId = 7,
                            Category = "Password",
                            Description = "Advanced password recovery",
                            ToolName = "Hashcat"
                        },
                        new
                        {
                            ToolId = 8,
                            Category = "Web",
                            Description = "SQL injection tool",
                            ToolName = "SQLMap"
                        },
                        new
                        {
                            ToolId = 9,
                            Category = "Web",
                            Description = "Web server scanner",
                            ToolName = "Nikto"
                        },
                        new
                        {
                            ToolId = 10,
                            Category = "Web",
                            Description = "Web app security scanner",
                            ToolName = "OWASP ZAP"
                        },
                        new
                        {
                            ToolId = 11,
                            Category = "Password",
                            Description = "Network login cracker",
                            ToolName = "Hydra"
                        },
                        new
                        {
                            ToolId = 12,
                            Category = "Vulnerability",
                            Description = "Vulnerability scanner",
                            ToolName = "Nessus"
                        },
                        new
                        {
                            ToolId = 13,
                            Category = "Vulnerability",
                            Description = "Vulnerability management",
                            ToolName = "OpenVAS"
                        },
                        new
                        {
                            ToolId = 14,
                            Category = "Network",
                            Description = "Fast port scanner",
                            ToolName = "Masscan"
                        },
                        new
                        {
                            ToolId = 15,
                            Category = "Web",
                            Description = "Web content scanner",
                            ToolName = "Dirb"
                        },
                        new
                        {
                            ToolId = 16,
                            Category = "Web",
                            Description = "Directory/file brute forcer",
                            ToolName = "Gobuster"
                        },
                        new
                        {
                            ToolId = 17,
                            Category = "Vulnerability",
                            Description = "Vulnerability scanner",
                            ToolName = "Nuclei"
                        },
                        new
                        {
                            ToolId = 18,
                            Category = "Reconnaissance",
                            Description = "Subdomain discovery",
                            ToolName = "Subfinder"
                        },
                        new
                        {
                            ToolId = 19,
                            Category = "Reconnaissance",
                            Description = "In-depth attack surface mapping",
                            ToolName = "Amass"
                        },
                        new
                        {
                            ToolId = 20,
                            Category = "Reconnaissance",
                            Description = "Shodan search interface",
                            ToolName = "Shodan CLI"
                        },
                        new
                        {
                            ToolId = 21,
                            Category = "Reconnaissance",
                            Description = "Email/subdomain/people harvester",
                            ToolName = "TheHarvester"
                        },
                        new
                        {
                            ToolId = 22,
                            Category = "Reconnaissance",
                            Description = "Reconnaissance framework",
                            ToolName = "Recon-ng"
                        },
                        new
                        {
                            ToolId = 23,
                            Category = "Reconnaissance",
                            Description = "Link analysis tool",
                            ToolName = "Maltego"
                        },
                        new
                        {
                            ToolId = 24,
                            Category = "Exploitation",
                            Description = "Adversary simulation",
                            ToolName = "Cobalt Strike"
                        },
                        new
                        {
                            ToolId = 25,
                            Category = "Exploitation",
                            Description = "Post-exploitation framework",
                            ToolName = "Empire"
                        },
                        new
                        {
                            ToolId = 26,
                            Category = "Post-Exploitation",
                            Description = "Credential extraction",
                            ToolName = "Mimikatz"
                        },
                        new
                        {
                            ToolId = 27,
                            Category = "Post-Exploitation",
                            Description = "Active Directory analysis",
                            ToolName = "BloodHound"
                        },
                        new
                        {
                            ToolId = 28,
                            Category = "Post-Exploitation",
                            Description = "Network protocols library",
                            ToolName = "Impacket"
                        },
                        new
                        {
                            ToolId = 29,
                            Category = "Post-Exploitation",
                            Description = "LLMNR/NBT-NS poisoner",
                            ToolName = "Responder"
                        },
                        new
                        {
                            ToolId = 30,
                            Category = "Network",
                            Description = "Network attack framework",
                            ToolName = "Bettercap"
                        },
                        new
                        {
                            ToolId = 31,
                            Category = "Network",
                            Description = "Network security tool",
                            ToolName = "Ettercap"
                        },
                        new
                        {
                            ToolId = 32,
                            Category = "Network",
                            Description = "Network monitor",
                            ToolName = "EtherApe"
                        },
                        new
                        {
                            ToolId = 33,
                            Category = "Network",
                            Description = "Packet analyzer",
                            ToolName = "Tcpdump"
                        },
                        new
                        {
                            ToolId = 34,
                            Category = "Network",
                            Description = "Network utility",
                            ToolName = "Netcat"
                        },
                        new
                        {
                            ToolId = 35,
                            Category = "Network",
                            Description = "Network relay",
                            ToolName = "Socat"
                        },
                        new
                        {
                            ToolId = 36,
                            Category = "Web",
                            Description = "SSL/TLS scanner",
                            ToolName = "SSLyze"
                        },
                        new
                        {
                            ToolId = 37,
                            Category = "Web",
                            Description = "SSL/TLS tester",
                            ToolName = "TestSSL"
                        },
                        new
                        {
                            ToolId = 38,
                            Category = "Web",
                            Description = "Web technology identifier",
                            ToolName = "WhatWeb"
                        },
                        new
                        {
                            ToolId = 39,
                            Category = "Web",
                            Description = "WordPress vulnerability scanner",
                            ToolName = "WPScan"
                        },
                        new
                        {
                            ToolId = 40,
                            Category = "Web",
                            Description = "XSS detection suite",
                            ToolName = "XSStrike"
                        },
                        new
                        {
                            ToolId = 41,
                            Category = "Web",
                            Description = "Command injection tool",
                            ToolName = "Commix"
                        },
                        new
                        {
                            ToolId = 42,
                            Category = "Web",
                            Description = "XXE injection tool",
                            ToolName = "XXEinjector"
                        },
                        new
                        {
                            ToolId = 43,
                            Category = "Web",
                            Description = "JSON Web Token toolkit",
                            ToolName = "JWT Tool"
                        },
                        new
                        {
                            ToolId = 44,
                            Category = "Code Analysis",
                            Description = "Git secrets scanner",
                            ToolName = "GitLeaks"
                        },
                        new
                        {
                            ToolId = 45,
                            Category = "Code Analysis",
                            Description = "Git credential scanner",
                            ToolName = "TruffleHog"
                        },
                        new
                        {
                            ToolId = 46,
                            Category = "Code Analysis",
                            Description = "Python security linter",
                            ToolName = "Bandit"
                        },
                        new
                        {
                            ToolId = 47,
                            Category = "Code Analysis",
                            Description = "Static analysis tool",
                            ToolName = "Semgrep"
                        },
                        new
                        {
                            ToolId = 48,
                            Category = "Code Analysis",
                            Description = "Code quality and security",
                            ToolName = "SonarQube"
                        },
                        new
                        {
                            ToolId = 49,
                            Category = "Code Analysis",
                            Description = "JavaScript dependency checker",
                            ToolName = "Retire.js"
                        },
                        new
                        {
                            ToolId = 50,
                            Category = "Code Analysis",
                            Description = "Vulnerability scanner",
                            ToolName = "Snyk"
                        },
                        new
                        {
                            ToolId = 51,
                            Category = "Container",
                            Description = "Docker security checker",
                            ToolName = "Docker Bench"
                        },
                        new
                        {
                            ToolId = 52,
                            Category = "Container",
                            Description = "Kubernetes security checker",
                            ToolName = "Kube-bench"
                        },
                        new
                        {
                            ToolId = 53,
                            Category = "Container",
                            Description = "Kubernetes penetration tool",
                            ToolName = "Kube-hunter"
                        },
                        new
                        {
                            ToolId = 54,
                            Category = "Container",
                            Description = "Container scanner",
                            ToolName = "Trivy"
                        },
                        new
                        {
                            ToolId = 55,
                            Category = "Container",
                            Description = "Container vulnerability scanner",
                            ToolName = "Clair"
                        },
                        new
                        {
                            ToolId = 56,
                            Category = "System",
                            Description = "Security auditing tool",
                            ToolName = "Lynis"
                        },
                        new
                        {
                            ToolId = 57,
                            Category = "System",
                            Description = "Rootkit detector",
                            ToolName = "Chkrootkit"
                        },
                        new
                        {
                            ToolId = 58,
                            Category = "System",
                            Description = "Rootkit hunter",
                            ToolName = "Rkhunter"
                        },
                        new
                        {
                            ToolId = 59,
                            Category = "System",
                            Description = "Intrusion prevention",
                            ToolName = "Fail2ban"
                        },
                        new
                        {
                            ToolId = 60,
                            Category = "System",
                            Description = "Intrusion detection",
                            ToolName = "Snort"
                        },
                        new
                        {
                            ToolId = 61,
                            Category = "System",
                            Description = "Network security monitoring",
                            ToolName = "Suricata"
                        },
                        new
                        {
                            ToolId = 62,
                            Category = "System",
                            Description = "Network analysis framework",
                            ToolName = "Zeek"
                        });
                });

            modelBuilder.Entity("PentestHub.API.Data.Models.ToolInstallation", b =>
                {
                    b.Property<int>("InstallationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("InstallationId"));

                    b.Property<string>("InstallationPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("InstalledAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastVerifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ToolId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("InstallationId");

                    b.HasIndex("ToolId");

                    b.HasIndex("UserId", "ToolId")
                        .IsUnique();

                    b.ToTable("ToolInstallations");
                });

            modelBuilder.Entity("PentestHub.API.Data.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsTwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ResetToken")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ResetTokenExpires")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("TwoFactorSecret")
                        .HasColumnType("longtext");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PentestHub.API.Data.Models.AIConversation", b =>
                {
                    b.HasOne("PentestHub.API.Data.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PentestHub.API.Data.Models.LabResult", b =>
                {
                    b.HasOne("PentestHub.API.Data.Models.Lab", "Lab")
                        .WithMany()
                        .HasForeignKey("LabId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PentestHub.API.Data.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lab");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PentestHub.API.Data.Models.Notification", b =>
                {
                    b.HasOne("PentestHub.API.Data.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PentestHub.API.Data.Models.Report", b =>
                {
                    b.HasOne("PentestHub.API.Data.Models.ScanHistory", "ScanHistory")
                        .WithMany()
                        .HasForeignKey("ScanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PentestHub.API.Data.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScanHistory");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PentestHub.API.Data.Models.ScanHistory", b =>
                {
                    b.HasOne("PentestHub.API.Data.Models.Tool", "Tool")
                        .WithMany()
                        .HasForeignKey("ToolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PentestHub.API.Data.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tool");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PentestHub.API.Data.Models.ToolInstallation", b =>
                {
                    b.HasOne("PentestHub.API.Data.Models.Tool", "Tool")
                        .WithMany()
                        .HasForeignKey("ToolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PentestHub.API.Data.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tool");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PentestHub.API.Data.Models.User", b =>
                {
                    b.HasOne("PentestHub.API.Data.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });
#pragma warning restore 612, 618
        }
    }
}
